
// eslint-disable-next-line @typescript-eslint/consistent-type-assertions
export const scoreRes = {
  xh: '6105119047',
  terms_gpa: {
    '2019-2020-1': '2.510',
    '2019-2020-2': '2.513',
    '2020-2021-1': '2.757',
    '2020-2021-2': '2.987',
    '2021-2022-1': '3.000',
  },
  msg: '完成',
  total: 7,
  xm: '李清栋',
  terms: [
    '2019-2020-0',
    '2019-2020-1',
    '2019-2020-2',
    '2020-2021-0',
    '2020-2021-1',
    '2020-2021-2',
    '2021-2022-0',
  ],
  scores: [
    [
      {
        exam_type: '通过制',
        score: 75,
        include: false,
        lesson_name: '军事技能训练',
        course_type: '通识课（Ⅰ类）',
        grade_point: 2.7,
        lesson_type: '必修',
        term: '2019-2020-0',
        credit: 0.0,
      },
    ],
    [
      {
        exam_type: '正常考试',
        score: 88,
        include: true,
        lesson_name: 'C程序设计实验',
        course_type: '学科基础课',
        grade_point: 1.7,
        lesson_type: '必修',
        term: '2019-2020-1',
        credit: 1.0,
      },
      {
        exam_type: '正常考试',
        score: 78,
        include: true,
        lesson_name: '计算机应用基础',
        course_type: '通识课（Ⅰ类）',
        grade_point: 2.0,
        lesson_type: '必修',
        term: '2019-2020-1',
        credit: 1.5,
      },
      {
        exam_type: '正常考试',
        score: 79,
        include: true,
        lesson_name: '计算机应用基础实验',
        course_type: '通识课（Ⅰ类）',
        grade_point: 0.0,
        lesson_type: '必修',
        term: '2019-2020-1',
        credit: 1.0,
      },
      {
        exam_type: '正常考试',
        score: 83,
        include: true,
        lesson_name: '学科导论课',
        course_type: '通识课（Ⅰ类）',
        grade_point: 3.3,
        lesson_type: '必修',
        term: '2019-2020-1',
        credit: 1.0,
      },
      {
        exam_type: '正常考试',
        score: 83,
        include: true,
        lesson_name: '体育（1）',
        course_type: '通识课（Ⅰ类）',
        grade_point: 3.3,
        lesson_type: '必修',
        term: '2019-2020-1',
        credit: 1.0,
      },
      {
        exam_type: '正常考试',
        score: 83,
        include: true,
        lesson_name: '大学英语（1）',
        course_type: '通识课（Ⅰ类）',
        grade_point: 1.7,
        lesson_type: '必修',
        term: '2019-2020-1',
        credit: 3.0,
      },
      {
        exam_type: '正常考试',
        score: 72,
        include: true,
        lesson_name: '军事理论',
        course_type: '通识课（Ⅰ类）',
        grade_point: 3.0,
        lesson_type: '必修',
        term: '2019-2020-1',
        credit: 1.5,
      },
      {
        exam_type: '正常考试',
        score: 86,
        include: true,
        lesson_name: '形势与政策（1）',
        course_type: '通识课（Ⅰ类）',
        grade_point: 3.7,
        lesson_type: '必修',
        term: '2019-2020-1',
        credit: 0.5,
      },
      {
        exam_type: '补考一',
        score: 81,
        include: true,
        lesson_name: '计算机应用基础实验',
        course_type: '通识课（Ⅰ类）',
        grade_point: 1.0,
        lesson_type: '必修',
        term: '2019-2020-1',
        credit: 1.0,
      },
      {
        exam_type: '正常考试',
        score: 72,
        include: true,
        lesson_name: '高等数学(Ⅰ)上',
        course_type: '学科基础课',
        grade_point: 2.3,
        lesson_type: '必修',
        term: '2019-2020-1',
        credit: 5.0,
      },
      {
        exam_type: '正常考试',
        score: 85,
        include: true,
        lesson_name: 'C程序设计',
        course_type: '学科基础课',
        grade_point: 2.0,
        lesson_type: '必修',
        term: '2019-2020-1',
        credit: 1.5,
      },
      {
        exam_type: '正常考试',
        score: 78,
        include: true,
        lesson_name: '工程制图（Ⅲ）',
        course_type: '学科基础课',
        grade_point: 2.0,
        lesson_type: '必修',
        term: '2019-2020-1',
        credit: 2.5,
      },
    ],
    [
      {
        exam_type: '补考一',
        score: 70,
        include: true,
        lesson_name: '线性代数',
        course_type: '学科基础课',
        grade_point: 1.0,
        lesson_type: '必修',
        term: '2019-2020-2',
        credit: 2.0,
      },
      {
        exam_type: '正常考试',
        score: 86,
        include: true,
        lesson_name: '形势与政策（2）',
        course_type: '通识课（Ⅰ类）',
        grade_point: 3.7,
        lesson_type: '必修',
        term: '2019-2020-2',
        credit: 0.5,
      },
      {
        exam_type: '正常考试',
        score: 83,
        include: true,
        lesson_name: '影视中的法律',
        grade_point: 3.3,
        course_type: '通识课（Ⅱ类）',
        lesson_type: '公选',
        term: '2019-2020-2',
        credit: 2.0,
      },
      {
        exam_type: '正常考试',
        score: 92,
        include: true,
        lesson_name: '土地经济学',
        grade_point: 4.0,
        course_type: '通识课（Ⅱ类）',
        lesson_type: '公选',
        term: '2019-2020-2',
        credit: 2.0,
      },
      {
        exam_type: '正常考试',
        score: 75,
        include: true,
        lesson_name: '高等数学(Ⅰ)下',
        course_type: '学科基础课',
        grade_point: 2.7,
        lesson_type: '必修',
        term: '2019-2020-2',
        credit: 5.0,
      },
      {
        exam_type: '正常考试',
        score: 77,
        include: true,
        lesson_name: '数据结构',
        course_type: '学科基础课',
        grade_point: 2.7,
        lesson_type: '必修',
        term: '2019-2020-2',
        credit: 1.5,
      },
      {
        exam_type: '正常考试',
        score: 79,
        include: true,
        lesson_name: '中国战“役”大思政',
        grade_point: 3.0,
        course_type: '通识课（Ⅱ类）',
        lesson_type: '公选',
        term: '2019-2020-2',
        credit: 1.0,
      },
      {
        exam_type: '正常考试',
        score: 86,
        include: true,
        lesson_name: '中国近现代史纲要',
        course_type: '通识课（Ⅰ类）',
        grade_point: 3.7,
        lesson_type: '必修',
        term: '2019-2020-2',
        credit: 2.0,
      },
      {
        exam_type: '正常考试',
        score: 88,
        include: true,
        lesson_name: '数据结构实验',
        course_type: '学科基础课',
        grade_point: 3.7,
        lesson_type: '必修',
        term: '2019-2020-2',
        credit: 1.0,
      },
      {
        exam_type: '正常考试',
        score: 62,
        include: true,
        lesson_name: '大学物理(Ⅰ)上',
        course_type: '学科基础课',
        grade_point: 1.7,
        lesson_type: '必修',
        term: '2019-2020-2',
        credit: 4.0,
      },
      {
        exam_type: '正常考试',
        score: 79,
        include: true,
        lesson_name: '电路分析',
        course_type: '学科基础课',
        grade_point: 3.0,
        lesson_type: '必修',
        term: '2019-2020-2',
        credit: 5.0,
      },
      {
        exam_type: '正常考试',
        score: 93,
        include: true,
        lesson_name: '大学生心理健康指导',
        course_type: '通识课（Ⅰ类）',
        grade_point: 4.0,
        lesson_type: '必修',
        term: '2019-2020-2',
        credit: 1.0,
      },
      {
        exam_type: '正常考试',
        score: 85,
        include: true,
        lesson_name: '体育（2）',
        course_type: '通识课（Ⅰ类）',
        grade_point: 3.7,
        lesson_type: '必修',
        term: '2019-2020-2',
        credit: 1.0,
      },
      {
        exam_type: '正常考试',
        score: 61,
        include: true,
        lesson_name: '大学英语（2）',
        course_type: '通识课（Ⅰ类）',
        grade_point: 1.3,
        lesson_type: '必修',
        term: '2019-2020-2',
        credit: 3.0,
      },
      {
        exam_type: '正常考试',
        score: 48,
        include: true,
        lesson_name: '线性代数',
        course_type: '学科基础课',
        grade_point: 0.0,
        lesson_type: '必修',
        term: '2019-2020-2',
        credit: 2.0,
      },
      {
        exam_type: '正常考试',
        score: 84,
        include: true,
        lesson_name: '大学生职业发展与就业指导',
        course_type: '通识课（Ⅰ类）',
        grade_point: 3.3,
        lesson_type: '必修',
        term: '2019-2020-2',
        credit: 1.0,
      },
      {
        exam_type: '正常考试',
        score: 63,
        include: true,
        lesson_name: '大学物理实验(Ⅰ)上',
        course_type: '学科基础课',
        grade_point: 1.7,
        lesson_type: '必修',
        term: '2019-2020-2',
        credit: 1.0,
      },
      {
        exam_type: '正常考试',
        score: 76,
        include: true,
        lesson_name: '电路分析实验',
        course_type: '学科基础课',
        grade_point: 2.7,
        lesson_type: '必修',
        term: '2019-2020-2',
        credit: 0.5,
      },
      {
        exam_type: '正常考试',
        score: 72,
        include: true,
        lesson_name: '思想道德修养与法律基础',
        course_type: '通识课（Ⅰ类）',
        grade_point: 2.3,
        lesson_type: '必修',
        term: '2019-2020-2',
        credit: 3.0,
      },
    ],
    [
      {
        exam_type: '正常考试',
        score: 85,
        include: true,
        lesson_name: '认识实习',
        course_type: '专业主干课',
        grade_point: 3.7,
        lesson_type: '必修',
        term: '2020-2021-0',
        credit: 0.0,
      },
      {
        exam_type: '正常考试',
        score: 73,
        include: true,
        lesson_name: '嵌入式C程序设计',
        course_type: '专业主干课',
        grade_point: 2.3,
        lesson_type: '必修',
        term: '2020-2021-0',
        credit: 1.0,
      },
      {
        exam_type: '正常考试',
        score: 88,
        include: true,
        lesson_name: '创新创业基础',
        course_type: '通识课（Ⅰ类）',
        grade_point: 3.7,
        lesson_type: '必修',
        term: '2020-2021-0',
        credit: 1.0,
      },
      {
        exam_type: '正常考试',
        score: 61,
        include: true,
        lesson_name: '电工电子实习(Ⅰ)',
        course_type: '学科基础课',
        grade_point: 1.3,
        lesson_type: '必修',
        term: '2020-2021-0',
        credit: 1.0,
      },
    ],
    [
      {
        exam_type: '正常考试',
        score: 74,
        include: true,
        lesson_name: '低频电子线路',
        course_type: '学科基础课',
        grade_point: 0.0,
        lesson_type: '必修',
        term: '2020-2021-1',
        credit: 3.5,
      },
      {
        exam_type: '正常考试',
        score: 75,
        include: true,
        lesson_name: '体育（3）',
        course_type: '通识课（Ⅰ类）',
        grade_point: 2.7,
        lesson_type: '必修',
        term: '2020-2021-1',
        credit: 0.5,
      },
      {
        exam_type: '正常考试',
        score: 78,
        include: true,
        lesson_name: '大学物理实验(Ⅰ)下',
        course_type: '学科基础课',
        grade_point: 3.0,
        lesson_type: '必修',
        term: '2020-2021-1',
        credit: 1.0,
      },
      {
        exam_type: '正常考试',
        score: 88,
        include: true,
        lesson_name: '形势与政策（3）',
        course_type: '通识课（Ⅰ类）',
        grade_point: 3.7,
        lesson_type: '必修',
        term: '2020-2021-1',
        credit: 0.5,
      },
      {
        exam_type: '正常考试',
        score: 87,
        include: true,
        lesson_name: '修辞学',
        grade_point: 3.7,
        course_type: '通识课（Ⅱ类）',
        lesson_type: '公选',
        term: '2020-2021-1',
        credit: 2.0,
      },
      {
        exam_type: '正常考试',
        score: 64,
        include: true,
        lesson_name: '概率论与数理统计(Ⅱ)',
        course_type: '学科基础课',
        grade_point: 1.7,
        lesson_type: '必修',
        term: '2020-2021-1',
        credit: 3.0,
      },
      {
        exam_type: '正常考试',
        score: 86,
        include: true,
        lesson_name: '毛泽东思想和中国特色社会主义理论体系概论',
        course_type: '通识课（Ⅰ类）',
        grade_point: 3.7,
        lesson_type: '必修',
        term: '2020-2021-1',
        credit: 6.0,
      },
      {
        exam_type: '正常考试',
        score: 83,
        include: true,
        lesson_name: '低频电子线路实验',
        course_type: '学科基础课',
        grade_point: 3.3,
        lesson_type: '必修',
        term: '2020-2021-1',
        credit: 1.0,
      },
      {
        exam_type: '正常考试',
        score: 77,
        include: true,
        lesson_name: '大国争锋：由一战到二战',
        grade_point: 2.7,
        course_type: '通识课（Ⅱ类）',
        lesson_type: '公选',
        term: '2020-2021-1',
        credit: 2.0,
      },
      {
        exam_type: '正常考试',
        score: 72,
        include: true,
        lesson_name: '数字系统与逻辑设计',
        course_type: '学科基础课',
        grade_point: 2.3,
        lesson_type: '必修',
        term: '2020-2021-1',
        credit: 3.5,
      },
      {
        exam_type: '正常考试',
        score: 82,
        include: true,
        lesson_name: '复变函数与积分变换',
        course_type: '学科基础课',
        grade_point: 3.3,
        lesson_type: '必修',
        term: '2020-2021-1',
        credit: 2.0,
      },
      {
        exam_type: '正常考试',
        score: 76,
        include: true,
        lesson_name: '大学物理(Ⅰ)下',
        course_type: '学科基础课',
        grade_point: 2.7,
        lesson_type: '必修',
        term: '2020-2021-1',
        credit: 3.0,
      },
      {
        exam_type: '正常考试',
        score: 79,
        include: true,
        lesson_name: '数字系统与逻辑设计实验',
        course_type: '学科基础课',
        grade_point: 3.0,
        lesson_type: '必修',
        term: '2020-2021-1',
        credit: 1.0,
      },
      {
        exam_type: '正常考试',
        score: 80,
        include: true,
        lesson_name: '通用外语类',
        course_type: '通识课（Ⅰ类）',
        grade_point: 3.0,
        lesson_type: '必修',
        term: '2020-2021-1',
        credit: 2.0,
      },
      {
        exam_type: '补考一',
        score: 70,
        include: true,
        lesson_name: '低频电子线路',
        course_type: '学科基础课',
        grade_point: 1.0,
        lesson_type: '必修',
        term: '2020-2021-1',
        credit: 3.5,
      },
    ],
    [
      {
        exam_type: '正常考试',
        score: 75,
        include: true,
        lesson_name: '马克思主义基本原理',
        course_type: '通识课（Ⅰ类）',
        grade_point: 2.7,
        lesson_type: '必修',
        term: '2020-2021-2',
        credit: 3.0,
      },
      {
        exam_type: '正常考试',
        score: 72,
        include: true,
        lesson_name: '嵌入式实时操作系统',
        grade_point: 2.3,
        course_type: '专业选修课',
        lesson_type: '选修',
        term: '2020-2021-2',
        credit: 2.0,
      },
      {
        exam_type: '正常考试',
        score: 79,
        include: true,
        lesson_name: '数理方程与特殊函数',
        course_type: '学科基础课',
        grade_point: 3.0,
        lesson_type: '必修',
        term: '2020-2021-2',
        credit: 2.0,
      },
      {
        exam_type: '正常考试',
        score: 73,
        include: true,
        lesson_name: '学术英语',
        course_type: '通识课（Ⅰ类）',
        grade_point: 2.3,
        lesson_type: '必修',
        term: '2020-2021-2',
        credit: 2.0,
      },
      {
        exam_type: '重修一',
        score: 89,
        include: true,
        lesson_name: '线性代数',
        course_type: '学科基础课',
        grade_point: 1.0,
        lesson_type: '必修',
        term: '2020-2021-2',
        credit: 2.0,
      },
      {
        exam_type: '正常考试',
        score: 87,
        include: true,
        lesson_name: '体育（4）',
        course_type: '通识课（Ⅰ类）',
        grade_point: 3.7,
        lesson_type: '必修',
        term: '2020-2021-2',
        credit: 0.5,
      },
      {
        exam_type: '正常考试',
        score: 87,
        include: true,
        lesson_name: 'Java程序设计实验',
        grade_point: 3.7,
        course_type: '专业选修课',
        lesson_type: '选修',
        term: '2020-2021-2',
        credit: 1.0,
      },
      {
        exam_type: '正常考试',
        score: 87,
        include: true,
        lesson_name: 'Java程序设计',
        grade_point: 3.7,
        course_type: '专业选修课',
        lesson_type: '选修',
        term: '2020-2021-2',
        credit: 1.5,
      },
      {
        exam_type: '正常考试',
        score: 76,
        include: true,
        lesson_name: '单片微型计算机原理及接口技术实验',
        course_type: '专业主干课',
        grade_point: 2.7,
        lesson_type: '必修',
        term: '2020-2021-2',
        credit: 1.0,
      },
      {
        exam_type: '正常考试',
        score: 73,
        include: true,
        lesson_name: '单片微型计算机原理及接口技术',
        course_type: '专业主干课',
        grade_point: 2.3,
        lesson_type: '必修',
        term: '2020-2021-2',
        credit: 3.5,
      },
      {
        exam_type: '正常考试',
        score: 90,
        include: true,
        lesson_name: '形势与政策（4）',
        course_type: '通识课（Ⅰ类）',
        grade_point: 4.0,
        lesson_type: '必修',
        term: '2020-2021-2',
        credit: 0.5,
      },
      {
        exam_type: '正常考试',
        score: 60,
        include: true,
        lesson_name: '信号与系统',
        course_type: '专业主干课',
        grade_point: 1.3,
        lesson_type: '必修',
        term: '2020-2021-2',
        credit: 3.5,
      },
    ],
    [
      {
        exam_type: '正常考试',
        score: 78,
        include: true,
        lesson_name: '电子线路设计与测试',
        course_type: '专业主干课',
        grade_point: 3.0,
        lesson_type: '必修',
        term: '2021-2022-0',
        credit: 1.0,
      },
    ],
  ],
  credits: 120.0,
  terms_gpa_split: {
    '2019-2020-1': '2.710',
    '2019-2020-2': '2.913',
    '2020-2021-0': '2.833',
    '2020-2021-1': '2.959',
    '2020-2021-2': '2.787',
    '2021-2022-0': '3.000',
  },
  status: 1,
} as ResType;

export interface ResType {
  xh: string;
  terms_gpa: {
    [time: string]: string;
  };
  msg: string;
  total: number;
  xm: string;
  terms: string[];
  scores: ScoreType[][];
  credits: number;
  terms_gpa_split: {
    [time: string]: string;
  };
}

export interface ScoreType{
  exam_type: string;
  score: number;
  include: boolean;
  lesson_name: string;
  course_type: string;
  grade_point: number;
  lesson_type: string;
  term: string;
  credit: number;
}
